
swagger: "2.0"
info:
  description: This is the swagger file that defines generated api
  version: "dev/0.0.1"
  title: API-Nlp Generated
consumes:
  - application/json
produces:
  - application/json

definitions:
  NLP:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: Id of the element
      createdAt:
        type: string
      updatedAt:
        type: string
      
      active:
        type: boolean

      name:
        type: string

      value:
        type: number



#base path for server application
basePath: /api
# Paths supported by the server application
paths:
  /nlp:
    get:
      operationId: api.listAll
      tags:
        - NLP
      summary: Read the entire list of nlp
      description: Read the list of nlp
      responses:
        200:
          description: Successfully read nlp list operation
          schema:
            $ref: '#/definitions/NLP'
    post:
      operationId: api.createOne
      tags:
        - NLP
      summary: Create a NLP and add it to the nlp list
      description: Create a new NLP in the nlp list
      parameters:
        - name: object
          in: body
          description: NLP to create
          required: True
          schema:
            $ref: '#/definitions/NLP'
      responses:
        201:
          description: Successfully created NLP in list

  /nlp/{id}:
    get:
      operationId: api.getOne
      tags:
        - NLP 
      summary: Read one NLP from the nlp list
      description: Read one NLP from the nlp list
      parameters:
        - name: id
          in: path
          description: Unique model identifier for NLP 
          type: string
          required: True
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            $ref: '#/definitions/NLP'
    put:
      operationId: api.updateOne
      tags:
        - NLP
      summary: Update a NLP in nlp 
      description: Update a NLP in nlp 
      parameters:
        - name: id
          in: path
          description: Unique model identifier for NLP
          type: string
          required: True
        - name: object
          in: body
          schema:
            $ref: '#/definitions/NLP'
      responses:
        200:
          description: Successfully updated NLP
    delete:
      operationId: api.deleteOne
      tags:
        - NLP
      summary: Delete a NLP from the nlp list
      description: Delete a person
      parameters:
        - name: id
          in: path
          type: string
          required: True
          description: Unique model identifier for NLP
      responses:
        200:
          description: Successfully deleted a NLP
